baseURL = "http://codebatik.com/"
languageCode = "en-us"
title = "Codebatik by Aditya"
theme = "hugo-tranquilpeak"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
pygmentsStyle = "monokai"
themesDir = "themes"

googleAnalytics = ""

[Params]
  Author = "Aditya Kresna Permana"

